config_version: 6 # DONT change this number

block_k: true #Block &k in chat messages, preventing players from using the magic formatting code.

mentioning:
  enabled: true
  requires_@: true # requires @ before the name to mention
  toggle_enabled: true # you can use /customchat mentiontoggle to toggle this feature per player
  enabled_default: true # is this feature enabled by default? in case false, players will need to enable it with the command
  op_disabled_default: true # op players, will have this feature disabled by default, they can enable it with the command
  sound: BLOCK_NOTE_BLOCK_PLING # leave "" to disable. List: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
  title:
    title: "&b{player} &ementioned you" # leave "" for not showing
    subtitle: "" # leave "" for not showing
    fadeIn: 10
    stay: 40
    fadeOut: 10
  message: "&b{player} &ementioned you. You can toggle this notification with &b/customchat mentiontoggle" # leave "" for not showing

discord_hook:
  enabled: false # Enable Discord webhook integration. All minecraft messages will be sent to the webhook.
  url: "https://discord.com/api/webhooks/xxxxxxxx/yyyyyyyyyyyy" # Your Discord webhook URL.
  username: "{player}" # Name of the webhook bot. You can use {player} placeholder.
  message: "**{player}**: {message}" # Message format sent to Discord. You can use {player} and {message} placeholders.
  embed:
    enabled: true # If enabled, messages will be sent as embeds.
    color_rgb: "8,139,168"
    title: "New Message from **{player}**" # You can use {player} placeholder.

database:
    type: sqlite #Database type, can be 'sqlite' or 'mysql'.
    mysql: #MySQL configuration. Only modify if using MySQL.
      host: "localhost" #MySQL host address.
      port: 3306 #MySQL port number.
      database: "customchat" #MySQL database name.
      username: "root" #MySQL username.
      password: "" #MySQL password.